<?php
	require '../../Models/Connection/connection_wo_token.php';

	$code = GET("ID");
	$countMe = 0;
	$result = $db->prepare("SELECT `risStorage` FROM `tblris` WHERE `risCode` = :ID");
	$result->execute([":ID"=>$code]);
	$row = $result->fetch();
	if ($row["risStorage"] == "1"){
		/*$result = $db->prepare("SELECT `risDate`, `risCode`, `campusName`, `supplyProperty`, `supplyUnit`, `supplyDesc`, `supplyCode`, `supplyName`,`risAvailable`, `risQuantity`, `statusDesc`, IFNULL(`usedQuantity`,  `risQuantity`) as `usedQuantity`, `risRemarks`, `officer`.`accountName` as `officerName`, `officer`.`accountPosition` as `officerPosition`, `officeOfficer`.`officeName` as `officerOffice`, `employee`.`accountName` as `employeeName`, `employee`.`accountPosition` as `employeePosition`, `officeEmployee`.`officeName` as `employeeOffice` FROM `tblrisdet` INNER JOIN `tblris` ON `tblris`.`risID` = `tblrisdet`.`risID` INNER JOIN `tblsupply` ON `tblsupply`.`supplyID` = `tblrisdet`.`supplyID` LEFT JOIN `tblsupplyused` ON `tblsupplyused`.`risID` = `tblris`.`risID`AND `tblrisdet`.`supplyID` = `tblsupplyused`.`supplyID` LEFT JOIN `tblsupplydesc` ON `tblsupplydesc`.`descID` = `tblsupplyused`.`descID` LEFT JOIN `tblstatus` ON `tblstatus`.`statusNo` = `tblrisdet`.`risStatus` AND `statusTable` = 'RIS'LEFT JOIN `tblaccount` `officer` ON `officer`.`accountID`  = `tblris`.`officerID` LEFT JOIN `tblaccount` `employee` ON `employee`.`accountID` = `tblris`.`employeeID` LEFT JOIN `tbloffices` `officeOfficer` ON `officeOfficer`.`officeID` = `officer`.`officeID` LEFT JOIN `tbloffices` `officeEmployee` ON `officeEmployee`.`officeID` = `employee`.`officeID` LEFT JOIN `tblcampus` ON `officeEmployee`.`campusID` = `tblcampus`.`campusID` WHERE `risCode` = :ID");*/
		$result = $db->prepare("SELECT `risDate`, `risCode`, `campusName`, `supplyProperty`, `supplyUnit`, `supplyDesc`, `supplyCode`, `supplyName`,`risAvailable`, `risQuantity`, `statusDesc`, IFNULL(`usedQuantity`,  `risQuantity`) as `usedQuantity`, `risRemarks`, `officer`.`accountName` as `officerName`, `officer`.`accountPosition` as `officerPosition`, `officeOfficer`.`officeName` as `officerOffice`, `employee`.`accountName` as `employeeName`, `employee`.`accountPosition` as `employeePosition`, `officeEmployee`.`officeName` as `employeeOffice` FROM `tblrisdet` INNER JOIN `tblris` ON `tblris`.`risID` = `tblrisdet`.`risID` INNER JOIN `tblsupply` ON `tblsupply`.`supplyID` = `tblrisdet`.`supplyID` LEFT JOIN `tblsupplyused` ON `tblsupplyused`.`risID` = `tblris`.`risID`AND `tblrisdet`.`supplyID` = `tblsupplyused`.`supplyID` LEFT JOIN `tblsupplydesc` ON `tblsupplydesc`.`descID` = `tblsupplyused`.`descID` LEFT JOIN `tblstatus` ON `tblstatus`.`statusNo` = `tblrisdet`.`risStatus` AND `statusTable` = 'RIS'LEFT JOIN `tblaccount` `officer` ON `officer`.`accountID`  = `tblris`.`officerID` LEFT JOIN `tblaccount` `employee` ON `employee`.`accountID` = `tblris`.`employeeID` LEFT JOIN `tbloffices` `officeOfficer` ON `officeOfficer`.`officeID` = `officer`.`officeID` LEFT JOIN `tbloffices` `officeEmployee` ON `officeEmployee`.`officeID` = `employee`.`officeID` LEFT JOIN `tblcampus` ON `officeEmployee`.`campusID` = `tblcampus`.`campusID` WHERE `risCode` = :ID");
	}else{
		/*$result = $db->prepare("SELECT `risDate`, `risCode`, `campusName`, `supplyProperty`, `supplyUnit`, `supplyDesc`, `supplyCode`, `supplyName`,`risAvailable`, `risQuantity`, `statusDesc`, `risQuantity` as `usedQuantity`, `risRemarks`, `officer`.`accountName` as `officerName`, `officer`.`accountPosition` as `officerPosition`, `officeOfficer`.`officeName` as `officerOffice`, `employee`.`accountName` as `employeeName`, `employee`.`accountPosition` as `employeePosition`, `officeEmployee`.`officeName` as `employeeOffice` FROM `tblrisdet` INNER JOIN `tblris` ON `tblris`.`risID` = `tblrisdet`.`risID` INNER JOIN `tblsupply` ON `tblsupply`.`supplyID` = `tblrisdet`.`supplyID` INNER JOIN `tblstockroom` ON `tblstockroom`.`srID` = `tblrisdet`.`stockID` INNER JOIN `tblstock` ON `tblstock`.`stockID` = `tblstockroom`.`stockID` LEFT JOIN `tblsupplydesc` ON `tblsupplydesc`.`descID` = `tblstock`.`descID` LEFT JOIN `tblstatus` ON `tblstatus`.`statusNo` = `tblrisdet`.`risStatus` AND `statusTable` = 'RIS'LEFT JOIN `tblaccount` `officer` ON `officer`.`accountID`  = `tblris`.`officerID` LEFT JOIN `tblaccount` `employee` ON `employee`.`accountID` = `tblris`.`employeeID` LEFT JOIN `tbloffices` `officeOfficer` ON `officeOfficer`.`officeID` = `officer`.`officeID` LEFT JOIN `tbloffices` `officeEmployee` ON `officeEmployee`.`officeID` = `employee`.`officeID` LEFT JOIN `tblcampus` ON `officeEmployee`.`campusID` = `tblcampus`.`campusID` WHERE `risCode` = :ID "); */
		$result = $db->prepare("SELECT `risDate`, `risCode`, `campusName`, `supplyProperty`, `supplyUnit`, `supplyDesc`, `supplyCode`, `supplyName`,`risAvailable`, `risQuantity`, `statusDesc`, `risQuantity` as `usedQuantity`, `risRemarks`, `officer`.`accountName` as `officerName`, `officer`.`accountPosition` as `officerPosition`, `officeOfficer`.`officeName` as `officerOffice`, `employee`.`accountName` as `employeeName`, `employee`.`accountPosition` as `employeePosition`, `officeEmployee`.`officeName` as `employeeOffice` FROM `tblrisdet` LEFT JOIN `tblris` ON `tblris`.`risID` = `tblrisdet`.`risID` LEFT JOIN `tblsupply` ON `tblsupply`.`supplyID` = `tblrisdet`.`supplyID` LEFT JOIN `tblstockroom` ON `tblstockroom`.`srID` = `tblrisdet`.`stockID` LEFT JOIN `tblstock` ON `tblstock`.`stockID` = `tblstockroom`.`stockID` LEFT JOIN `tblsupplydesc` ON `tblsupplydesc`.`descID` = `tblstock`.`descID` LEFT JOIN `tblstatus` ON `tblstatus`.`statusNo` = `tblrisdet`.`risStatus` AND `statusTable` = 'RIS'LEFT JOIN `tblaccount` `officer` ON `officer`.`accountID`  = `tblris`.`officerID` LEFT JOIN `tblaccount` `employee` ON `employee`.`accountID` = `tblris`.`employeeID` LEFT JOIN `tbloffices` `officeOfficer` ON `officeOfficer`.`officeID` = `officer`.`officeID` LEFT JOIN `tbloffices` `officeEmployee` ON `officeEmployee`.`officeID` = `employee`.`officeID` LEFT JOIN `tblcampus` ON `officeEmployee`.`campusID` = `tblcampus`.`campusID` WHERE `risCode` = :ID "); 
	}
	$result->execute([":ID"=>$code]);
	while($row = $result->fetch()){
		$supply = $row["supplyCode"] == "" ? $row["supplyName"] : $row['supplyName'] . " (" . $row['supplyCode'] .")";
		$supply = $row["supplyDesc"] == "" ? $supply : $supply . " - " . $row["supplyDesc"];
		$arrayRISPDF[] = array('DateRequest' => $row['risDate'], 'Code' => $row['risCode'], 'Campus' => $row['campusName'], 'Property' => $row['supplyProperty'], 'Available' => $row['risAvailable'], 'Unit' => $row['supplyUnit'], 'Supply' => $supply, 'Status' => $row['statusDesc'], 'Quantity' => $row['usedQuantity'], 'Remarks' => $row['risRemarks'], 'officerName' => $row['officerName'], 'officerPosition' => $row['officerPosition'], 'officerOffice' => $row['officerOffice'], 'employeeName' => $row['employeeName'], 'employeePosition' => $row['employeePosition'], 'employeeOffice' => $row['employeeOffice']);
		$countMe++;
	}

	EmptyReports("ID", "", $arrayRISPDF);
?>