<?php
	require '../../Models/Connection/connection_wo_token.php';
	$fund = GET("Fund");
	$supply = GET("Supply");
	$unit = GET("Unit");
	$desc = GET("Specific");
	$year = GET("Year");
	$warehouse = GET("Warehouse");
	$prevYear = $year - 1;
	$countMe = 0;
	$balance = 0;

	
	if($desc == "*"){
		if ($warehouse == "1"){
			$params = array(':supply_1' => $supply, ':unit_1' => $unit, ":fund_1" => $fund, ':year_1' => $year, ':supply_2' => $supply, ':unit_2' => $unit, ":fund_2" => $fund, ':year_2' => $year, ':supply_3' => $supply, ':unit_3' => $unit, ":fund_3" => $fund, ':prevYear' => $prevYear);

			$result = $db->prepare("SELECT `fundName`, `fundCode`, `supplyName`, `supplyUnit`, '' as `supplyDesc`, `supplyProperty`, 'Beginning Balance' as `Date`, '' as `Reference`, SUM(`stockBalance`) as `Balance`, '' as `Receipt`, '' as `Issue`, '' as `office` FROM `tblsupplydesc` INNER JOIN `tblstock` ON `tblstock`.`descID` = `tblsupplydesc`.`descID` INNER JOIN `tblpo` ON `tblpo`.`poID` = `tblstock`.`poID` INNER JOIN `tblfundcluster` ON `tblfundcluster`.`fundID` = `tblpo`.`fundID` INNER JOIN `tblsupply` ON `tblsupply`.`supplyID` = `tblsupplydesc`.`supplyID` WHERE `tblsupplydesc`.`supplyID` = :supply_1 AND `supplyUnit` = :unit_1 AND `supplyDesc` IS NULL AND YEAR(`DRDate`) <= :prevYear AND `tblpo`.`fundID` = :fund_1 GROUP BY `tblstock`.`supplyID` UNION ALL SELECT `fundName`, `fundCode`, `supplyName`, `supplyUnit`, '' as `supplyDesc`, `supplyProperty`, `DRDate` as `Date`, `DRCode` as `Reference`, 0 as `Balance`, `stockAvailable` as `Receipt`, 0 as `Issue`, '' as `office` FROM `tblsupplydesc` INNER JOIN `tblstock` ON `tblstock`.`descID` = `tblsupplydesc`.`descID` INNER JOIN `tblpo` ON `tblpo`.`poID` = `tblstock`.`poID` INNER JOIN `tblfundcluster` ON `tblfundcluster`.`fundID` = `tblpo`.`fundID` INNER JOIN `tblsupply` ON `tblsupply`.`supplyID` = `tblsupplydesc`.`supplyID` WHERE `tblsupplydesc`.`supplyID` = :supply_2 AND `supplyUnit` = :unit_2 AND `supplyDesc` IS NULL AND YEAR(`DRDate`) = :year_1  AND `tblpo`.`fundID` = :fund_2 UNION ALL SELECT `fundName`, `fundCode`, `supplyName`, `supplyUnit`, '' as `supplyDesc`, `supplyProperty`, `risDate` as `Date`, `risCode` as `Reference`, 0 as `Balance`, 0 as `Receipt`, `risAvailable` as `Issue`, `officeName` as `office` FROM `tblsupplydesc` INNER JOIN `tblstock` ON `tblstock`.`descID` = `tblsupplydesc`.`descID` INNER JOIN `tblrisdet` ON `tblrisdet`.`stockID` = `tblstock`.`stockID` INNER JOIN `tblpo` ON `tblpo`.`poID` = `tblstock`.`poID` INNER JOIN `tblfundcluster` ON `tblfundcluster`.`fundID` = `tblpo`.`fundID` INNER JOIN `tblris` ON `tblris`.`risID` = `tblrisdet`.`risID` INNER JOIN `tblaccount` ON `tblaccount`.`accountID` = `tblris`.`employeeID` INNER JOIN `tbloffices` ON `tbloffices`.`officeID` = `tblaccount`.`officeID` INNER JOIN `tblsupply` ON `tblsupply`.`supplyID` = `tblsupplydesc`.`supplyID` WHERE `tblsupplydesc`.`supplyID` = :supply_3 AND `supplyUnit` = :unit_3 AND `supplyDesc` IS NULL AND `risAvailable` != 0 AND YEAR(`RISDate`) = :year_2 AND `tblpo`.`fundID` = :fund_3"); 
			$result->execute($params);
		}else{
			$params = array(':supply_1' => $supply, ':unit_1' => $unit, ":fund_1" => $fund, ':year_1' => $year, ':supply_2' => $supply, ':unit_2' => $unit, ":fund_2" => $fund, ':year_2' => $year, ':supply_3' => $supply, ':unit_3' => $unit, ":fund_3" => $fund, ':prevYear' => $prevYear, ":warehouse_1" => $warehouse, ":warehouse_2" => $warehouse, ":warehouse_3" => $warehouse);
			$result = $db->prepare("SELECT `fundName`, `fundCode`, `supplyName`, `supplyUnit`, `supplyDesc`, `supplyProperty`, 'Beginning Balance' as `Date`, '' as `Reference`, SUM(`srBalance`) as `Balance`, '' as `Receipt`, '' as `Issue`, '' as `office` FROM `tblstockroom` INNER JOIN `tblstock` ON `tblstock`.`stockID` = `tblstockroom`.`stockID` INNER JOIN `tblsupplydesc` ON `tblsupplydesc`.`descID` = `tblstock`.`descID` INNER JOIN `tblpo` ON `tblpo`.`poID` = `tblstock`.`poID` INNER JOIN `tblfundcluster` ON `tblfundcluster`.`fundID` = `tblpo`.`fundID` INNER JOIN `tblsupply` ON `tblsupply`.`supplyID` = `tblsupplydesc`.`supplyID` WHERE `tblsupplydesc`.`supplyID` = :supply_1 AND `supplyUnit` = :unit_1 AND `supplyDesc`  IS NULL AND YEAR(`DRDate`) <= :prevYear AND `tblpo`.`fundID` = :fund_1 AND `warehouseID` = :warehouse_1 GROUP BY `tblstock`.`supplyID` UNION ALL SELECT `fundName`, `fundCode`, `supplyName`, `supplyUnit`, `supplyDesc`, `supplyProperty`, `DRDate` as `Date`, `DRCode` as `Reference`, 0 as `Balance`, `srBalance` as `Receipt`, 0 as `Issue`, '' as `office` FROM `tblstockroom` INNER JOIN `tblstock` ON `tblstock`.`stockID` = `tblstockroom`.`stockID` INNER JOIN `tblsupplydesc` ON `tblsupplydesc`.`descID` = `tblstock`.`descID` INNER JOIN `tblpo` ON `tblpo`.`poID` = `tblstock`.`poID` INNER JOIN `tblfundcluster` ON `tblfundcluster`.`fundID` = `tblpo`.`fundID` INNER JOIN `tblsupply` ON `tblsupply`.`supplyID` = `tblsupplydesc`.`supplyID` WHERE `tblsupplydesc`.`supplyID` = :supply_2 AND `supplyUnit` = :unit_2 AND `supplyDesc`  IS NULL AND YEAR(`DRDate`) = :year_1  AND `tblpo`.`fundID` = :fund_2 AND `warehouseID` = :warehouse_2 UNION ALL SELECT `fundName`, `fundCode`, `supplyName`, `supplyUnit`, `supplyDesc`, `supplyProperty`, `risDate` as `Date`, `risCode` as `Reference`, 0 as `Balance`, 0 as `Receipt`, `risAvailable` as `Issue`, `officeName` as `office` FROM `tblstockroom` INNER JOIN `tblstock` ON `tblstock`.`stockID` = `tblstockroom`.`stockID` INNER JOIN `tblsupplydesc` ON `tblsupplydesc`.`descID` = `tblstock`.`descID` INNER JOIN `tblrisdet` ON `tblrisdet`.`stockID` = `tblstockroom`.`srID` INNER JOIN `tblpo` ON `tblpo`.`poID` = `tblstock`.`poID` INNER JOIN `tblfundcluster` ON `tblfundcluster`.`fundID` = `tblpo`.`fundID` INNER JOIN `tblris` ON `tblris`.`risID` = `tblrisdet`.`risID` INNER JOIN `tblaccount` ON `tblaccount`.`accountID` = `tblris`.`employeeID` INNER JOIN `tbloffices` ON `tbloffices`.`officeID` = `tblaccount`.`officeID` INNER JOIN `tblsupply` ON `tblsupply`.`supplyID` = `tblsupplydesc`.`supplyID` WHERE `tblsupplydesc`.`supplyID` = :supply_3 AND `supplyUnit` = :unit_3 AND `supplyDesc`  IS NULL AND `risAvailable` != 0 AND YEAR(`RISDate`) = :year_2 AND `tblpo`.`fundID` = :fund_3 AND `warehouseID` = :warehouse_3");
			 $result->execute($params);
		}
	}else{
		if($warehouse == "1"){
			$params = array(':supply_1' => $supply, ':unit_1' => $unit, ':specific_1' => $desc, ":fund_1" => $fund, ':year_1' => $year, ':supply_2' => $supply, ':unit_2' => $unit, ':specific_2' => $desc, ":fund_2" => $fund, ':year_2' => $year, ':supply_3' => $supply, ':unit_3' => $unit, ':specific_3' => $desc, ":fund_3" => $fund, ':prevYear' => $prevYear);
			$result = $db->prepare("SELECT `fundName`, `fundCode`, `supplyName`, `supplyUnit`, `supplyDesc`, `supplyProperty`, 'Beginning Balance' as `Date`, '' as `Reference`, SUM(`stockBalance`) as `Balance`, '' as `Receipt`, '' as `Issue`, '' as `office` FROM `tblsupplydesc` INNER JOIN `tblstock` ON `tblstock`.`descID` = `tblsupplydesc`.`descID` INNER JOIN `tblpo` ON `tblpo`.`poID` = `tblstock`.`poID` INNER JOIN `tblfundcluster` ON `tblfundcluster`.`fundID` = `tblpo`.`fundID` INNER JOIN `tblsupply` ON `tblsupply`.`supplyID` = `tblsupplydesc`.`supplyID` WHERE `tblsupplydesc`.`supplyID` = :supply_1 AND `supplyUnit` = :unit_1 AND `supplyDesc` = :specific_1 AND YEAR(`DRDate`) <= :prevYear AND `tblpo`.`fundID` = :fund_1 GROUP BY `tblstock`.`supplyID` UNION ALL SELECT `fundName`, `fundCode`, `supplyName`, `supplyUnit`, `supplyDesc`, `supplyProperty`, `DRDate` as `Date`, `DRCode` as `Reference`, 0 as `Balance`, `stockAvailable` as `Receipt`, 0 as `Issue`, '' as `office` FROM `tblsupplydesc` INNER JOIN `tblstock` ON `tblstock`.`descID` = `tblsupplydesc`.`descID` INNER JOIN `tblpo` ON `tblpo`.`poID` = `tblstock`.`poID` INNER JOIN `tblfundcluster` ON `tblfundcluster`.`fundID` = `tblpo`.`fundID` INNER JOIN `tblsupply` ON `tblsupply`.`supplyID` = `tblsupplydesc`.`supplyID` WHERE `tblsupplydesc`.`supplyID` = :supply_2 AND `supplyUnit` = :unit_2 AND `supplyDesc` = :specific_2 AND YEAR(`DRDate`) = :year_1  AND `tblpo`.`fundID` = :fund_2 UNION ALL SELECT `fundName`, `fundCode`, `supplyName`, `supplyUnit`, `supplyDesc`, `supplyProperty`, `risDate` as `Date`, `risCode` as `Reference`, 0 as `Balance`, 0 as `Receipt`, `risAvailable` as `Issue`, `officeName` as `office` FROM `tblsupplydesc` INNER JOIN `tblstock` ON `tblstock`.`descID` = `tblsupplydesc`.`descID` INNER JOIN `tblrisdet` ON `tblrisdet`.`stockID` = `tblstock`.`stockID` INNER JOIN `tblpo` ON `tblpo`.`poID` = `tblstock`.`poID` INNER JOIN `tblfundcluster` ON `tblfundcluster`.`fundID` = `tblpo`.`fundID` INNER JOIN `tblris` ON `tblris`.`risID` = `tblrisdet`.`risID` INNER JOIN `tblaccount` ON `tblaccount`.`accountID` = `tblris`.`employeeID` INNER JOIN `tbloffices` ON `tbloffices`.`officeID` = `tblaccount`.`officeID` INNER JOIN `tblsupply` ON `tblsupply`.`supplyID` = `tblsupplydesc`.`supplyID` WHERE `tblsupplydesc`.`supplyID` = :supply_3 AND `supplyUnit` = :unit_3 AND `supplyDesc` = :specific_3 AND `risAvailable` != 0 AND YEAR(`RISDate`) = :year_2 AND `tblpo`.`fundID` = :fund_3"); 
			$result->execute($params);
		}else{
			$params = array(':supply_1' => $supply, ':unit_1' => $unit, ':specific_1' => $desc, ":fund_1" => $fund, ':year_1' => $year, ':supply_2' => $supply, ':unit_2' => $unit, ':specific_2' => $desc, ":fund_2" => $fund, ':year_2' => $year, ':supply_3' => $supply, ':unit_3' => $unit, ':specific_3' => $desc, ":fund_3" => $fund, ':prevYear' => $prevYear, ":warehouse_1" => $warehouse, ":warehouse_2" => $warehouse, ":warehouse_3" => $warehouse);
			$result = $db->prepare("SELECT `fundName`, `fundCode`, `supplyName`, `supplyUnit`, `supplyDesc`, `supplyProperty`, 'Beginning Balance' as `Date`, '' as `Reference`, SUM(`srBalance`) as `Balance`, '' as `Receipt`, '' as `Issue`, '' as `office` FROM `tblstockroom` INNER JOIN `tblstock` ON `tblstock`.`stockID` = `tblstockroom`.`stockID` INNER JOIN `tblsupplydesc` ON `tblsupplydesc`.`descID` = `tblstock`.`descID` INNER JOIN `tblpo` ON `tblpo`.`poID` = `tblstock`.`poID` INNER JOIN `tblfundcluster` ON `tblfundcluster`.`fundID` = `tblpo`.`fundID` INNER JOIN `tblsupply` ON `tblsupply`.`supplyID` = `tblsupplydesc`.`supplyID` WHERE `tblsupplydesc`.`supplyID` = :supply_1 AND `supplyUnit` = :unit_1 AND `supplyDesc` = :specific_1 AND YEAR(`DRDate`) <= :prevYear AND `tblpo`.`fundID` = :fund_1 AND `warehouseID` = :warehouse_1 GROUP BY `tblstock`.`supplyID` UNION ALL SELECT `fundName`, `fundCode`, `supplyName`, `supplyUnit`, `supplyDesc`, `supplyProperty`, `DRDate` as `Date`, `DRCode` as `Reference`, 0 as `Balance`, `srBalance` as `Receipt`, 0 as `Issue`, '' as `office` FROM `tblstockroom` INNER JOIN `tblstock` ON `tblstock`.`stockID` = `tblstockroom`.`stockID` INNER JOIN `tblsupplydesc` ON `tblsupplydesc`.`descID` = `tblstock`.`descID` INNER JOIN `tblpo` ON `tblpo`.`poID` = `tblstock`.`poID` INNER JOIN `tblfundcluster` ON `tblfundcluster`.`fundID` = `tblpo`.`fundID` INNER JOIN `tblsupply` ON `tblsupply`.`supplyID` = `tblsupplydesc`.`supplyID` WHERE `tblsupplydesc`.`supplyID` = :supply_2 AND `supplyUnit` = :unit_2 AND `supplyDesc` = :specific_2 AND YEAR(`DRDate`) = :year_1  AND `tblpo`.`fundID` = :fund_2 AND `warehouseID` = :warehouse_2 UNION ALL SELECT `fundName`, `fundCode`, `supplyName`, `supplyUnit`, `supplyDesc`, `supplyProperty`, `risDate` as `Date`, `risCode` as `Reference`, 0 as `Balance`, 0 as `Receipt`, `risAvailable` as `Issue`, `officeName` as `office` FROM `tblstockroom` INNER JOIN `tblstock` ON `tblstock`.`stockID` = `tblstockroom`.`stockID` INNER JOIN `tblsupplydesc` ON `tblsupplydesc`.`descID` = `tblstock`.`descID` INNER JOIN `tblrisdet` ON `tblrisdet`.`stockID` = `tblstockroom`.`srID` INNER JOIN `tblpo` ON `tblpo`.`poID` = `tblstock`.`poID` INNER JOIN `tblfundcluster` ON `tblfundcluster`.`fundID` = `tblpo`.`fundID` INNER JOIN `tblris` ON `tblris`.`risID` = `tblrisdet`.`risID` INNER JOIN `tblaccount` ON `tblaccount`.`accountID` = `tblris`.`employeeID` INNER JOIN `tbloffices` ON `tbloffices`.`officeID` = `tblaccount`.`officeID` INNER JOIN `tblsupply` ON `tblsupply`.`supplyID` = `tblsupplydesc`.`supplyID` WHERE `tblsupplydesc`.`supplyID` = :supply_3 AND `supplyUnit` = :unit_3 AND `supplyDesc` = :specific_3 AND `risAvailable` != 0 AND YEAR(`RISDate`) = :year_2 AND `tblpo`.`fundID` = :fund_3 AND `warehouseID` = :warehouse_3");
			$result->execute($params);
		}
		
	}
	while($row = $result->fetch()){
		$balance = $balance +  floatval($row["Balance"]) + floatval($row["Receipt"]) - floatval($row["Issue"]);
		$arrayStockCard[] = array("Fund" => $row["fundName"]." (". $row["fundCode"] .")", "Supply" => $row["supplyName"], "Unit" => $row["supplyUnit"], "Description" => $row["supplyDesc"], "StockNo" => $row["supplyProperty"],  "Date" => $row["Date"], "Reference" => $row["Reference"], "Balance" => $balance, "Receipt" => $row["Receipt"], "Issue" => $row["Issue"], "Office" => $row["office"]);
		$countMe++;
	}
	EmptyReports("Fund", "Reports/Stock_Card.php", $arrayStockCard);
	EmptyReports("Supply", "Reports/Stock_Card.php", "none");
	EmptyReports("Unit", "Reports/Stock_Card.php", "none");
	EmptyReports("Specific", "Reports/Stock_Card.php", "none");
	EmptyReports("Year", "Reports/Stock_Card.php", "none");
	EmptyReports("Warehouse", "Reports/Stock_Card.php", "none");

?>